Document: python-phabricator
Title: Debian python-phabricator Manual
Author: <insert document author here>
Abstract: This manual describes what python-phabricator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-phabricator/python-phabricator.sgml.gz

Format: postscript
Files: /usr/share/doc/python-phabricator/python-phabricator.ps.gz

Format: text
Files: /usr/share/doc/python-phabricator/python-phabricator.text.gz

Format: HTML
Index: /usr/share/doc/python-phabricator/html/index.html
Files: /usr/share/doc/python-phabricator/html/*.html
